### ISSUE TITLE
Conferences 

### ISSUE THREAD

**Issue by erikiva** [folkswhocode/awesome-diversity#17]
Are you adding conferences that make a special effort to be inclusive? For example this one: 
https://www.elixir-with-love.com/
They have a Diversity Ticket and include talks on mental health issues.

**Comment by dreamingechoes** [comment]
Omg! We dind’t have a proper section for conferences, but this one looks like the perfect one to start it. If you want, you can create a PR to add the new section and the first conference, so everyone could see that this section comes from you, or if you prefer, we can add it. What do you prefer? :smile:

**Comment by erikiva** [comment]
I can add It :)

**Comment by erikiva** [comment]
All done!

**Comment by dreamingechoes** [comment]
We can close this issue since you have addressed it in #16 😄
