### ISSUE TITLE
Delete advocates' section?

### ISSUE THREAD

**Issue by marinavega** [folkswhocode/awesome-diversity#2]
Should we delete advocates' section in order to avoid targeted harassment or bothering any member of the list?

**Comment by tasugo** [comment]
I think it can be a source of trouble for those listed if this repo gets popular, so I'd get rid of it altogether. Articles, videos, talks and even Twitter threads speak for themselves, the work of those advocates will still be in the repo, but not their specific Twitter handles.

There are some other options, such as emptying the section and allowing anyone to PR themselves into the list, but I don't think they're going to do that, so...

My 2¢.

**Comment by marinavega** [comment]
This is indeed a sensitive subject. We could empty the section and ask potential members for permission. What do you guys reckon?

**Comment by dreamingechoes** [comment]
100% agree with that 👏 😄

**Comment by dreamingechoes** [comment]
This is already done, so I'll close the issue! 😄
