### ISSUE TITLE
Proposal for a new community action [To give talks in high-schools]

### ISSUE THREAD

**Issue by jorgegalindocruces** [folkswhocode/awesome-diversity#24]
Hello folks,

Reading this [article of Rosa Rodriguez](https://www.paradigmadigital.com/techbiz/necesitamos-mas-wit/), I was thinking about the point sparked her vocation to be an engineer (not Jurassic Park movie 😂, the open-doors activity in the Faculty of Software Development).

In my city, a few of high schools around us, are contacting with our company to ask for give a talk in their classrooms (last year of the high school is the right moment to figure out your career). I think It could be awesome to organize a few of talks about the history of the technology to give in high schools, but from all the points of view, mentioning men and women that were key pieces into and try to share the message from an inclusive point of view. 

So, I propose:

- To use this movement to do a call to action of people/high-schools that want to give/receive talks.
- To use this repository to work between together on common slides to figure out the right way to share the message.
- To list the high schools, we contact and we do talks

I would like:

- To have a point of view from everyone, especially, from women in tech.

Cheers, and thank in advance!!!

**Comment by dreamingechoes** [comment]
Hi @jorgegalindocruces!

I love this proposal! But I think it would be better to discuss it in the new repository I just created for this kind of things, so would you mind to create an issue in https://github.com/folkswhocode/proposals?

Thank you very much for your contributions 😊 💖

**Comment by dreamingechoes** [comment]
Hi @jorgegalindocruces!

I have moved this proposal to https://github.com/folkswhocode/proposals/issues/1, so we can close this issue here and keep talking about the proposal there! 😄

Thank you! 💖
