### ISSUE TITLE
Add new article to "Posts"

### ISSUE THREAD

**Issue by maryjomadda** [folkswhocode/awesome-diversity#51]
[White Fragility in Teaching and Education Technology](https://www.edsurge.com/news/2018-08-23-white-fragility-in-teaching-and-education-an-interview-with-dr-robin-diangelo?utm_content=bufferaa5bd&utm_medium=social&utm_source=twitter.com&utm_campaign=EdSurgeBuffer) - By Mary Jo Madda

**Comment by dreamingechoes** [comment]
Hi @maryjomadda!

Thank you for this contribution! But in order to add the article to the repository, we need a pull request with the changes made. If you want, we can make ourselves the changes and add you to the contributors' list, what do you think? 😄 

Thank you! 😊

**Comment by maryjomadda** [comment]
Go for it!

**Comment by dreamingechoes** [comment]
Hi @maryjomadda!

I have already added the article to the list, so we can close this issue.

Again, thank you for this contribution! 😊
